[package]
name = "sukab-restaurant"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
actix-web = "4"
rand = "0"
env_logger = "0.11.3"
deadpool-postgres = "0.14.0"
tokio-postgres = "0.7.10"
log = "0.4.22"
